/* foods-db.js — Danh sách món Việt với calo KHẨU PHẦN ĐIỂN HÌNH (ước lượng phục vụ
   theo dõi cá nhân, không phải số liệu y khoa — quán khác nhau lệch ±20% là thường).
   Muốn thêm món hay ăn: thêm dòng vào đây, hoặc dùng "Nhập tay + Lưu vào món của tôi" trong app.
   cat: com | bun-pho | banh-xoi | do-uong | an-vat | khac */
(function (root) {
  'use strict';
  var FOODS_DB = [
    // ── Cơm ──────────────────────────────────────────
    { id: 'com-tam-suon', name: 'Cơm tấm sườn', kcal: 600, unit: '1 dĩa', cat: 'com' },
    { id: 'com-tam-suon-bi-cha', name: 'Cơm tấm sườn bì chả', kcal: 700, unit: '1 dĩa', cat: 'com' },
    { id: 'com-ga-xoi-mo', name: 'Cơm gà xối mỡ', kcal: 700, unit: '1 dĩa', cat: 'com' },
    { id: 'com-ga-luoc', name: 'Cơm gà luộc (Hải Nam)', kcal: 550, unit: '1 dĩa', cat: 'com' },
    { id: 'com-chien-duong-chau', name: 'Cơm chiên Dương Châu', kcal: 650, unit: '1 dĩa', cat: 'com' },
    { id: 'com-suon-kho', name: 'Cơm sườn kho', kcal: 600, unit: '1 dĩa', cat: 'com' },
    { id: 'com-thit-kho-trung', name: 'Cơm thịt kho trứng', kcal: 650, unit: '1 dĩa', cat: 'com' },
    { id: 'com-ca-kho', name: 'Cơm cá kho', kcal: 550, unit: '1 dĩa', cat: 'com' },
    { id: 'com-bo-luc-lac', name: 'Cơm bò lúc lắc', kcal: 650, unit: '1 dĩa', cat: 'com' },
    { id: 'com-van-phong', name: 'Cơm văn phòng (1 mặn 2 rau)', kcal: 550, unit: '1 phần', cat: 'com' },
    { id: 'com-cuon-han', name: 'Cơm cuộn (kimbap)', kcal: 450, unit: '1 cuộn', cat: 'com' },
    { id: 'com-trang', name: 'Cơm trắng', kcal: 200, unit: '1 chén', cat: 'com' },

    // ── Bún / Phở / Mì ───────────────────────────────
    { id: 'pho-bo', name: 'Phở bò', kcal: 450, unit: '1 tô', cat: 'bun-pho' },
    { id: 'pho-ga', name: 'Phở gà', kcal: 400, unit: '1 tô', cat: 'bun-pho' },
    { id: 'bun-bo-hue', name: 'Bún bò Huế', kcal: 550, unit: '1 tô', cat: 'bun-pho' },
    { id: 'bun-rieu', name: 'Bún riêu cua', kcal: 450, unit: '1 tô', cat: 'bun-pho' },
    { id: 'bun-thit-nuong', name: 'Bún thịt nướng', kcal: 550, unit: '1 tô', cat: 'bun-pho' },
    { id: 'bun-cha', name: 'Bún chả Hà Nội', kcal: 600, unit: '1 phần', cat: 'bun-pho' },
    { id: 'bun-mam', name: 'Bún mắm', kcal: 550, unit: '1 tô', cat: 'bun-pho' },
    { id: 'bun-ca', name: 'Bún cá', kcal: 450, unit: '1 tô', cat: 'bun-pho' },
    { id: 'hu-tieu-nam-vang', name: 'Hủ tiếu Nam Vang', kcal: 500, unit: '1 tô', cat: 'bun-pho' },
    { id: 'hu-tieu-go', name: 'Hủ tiếu gõ', kcal: 400, unit: '1 tô', cat: 'bun-pho' },
    { id: 'mi-quang', name: 'Mì Quảng', kcal: 550, unit: '1 tô', cat: 'bun-pho' },
    { id: 'cao-lau', name: 'Cao lầu', kcal: 500, unit: '1 tô', cat: 'bun-pho' },
    { id: 'mi-xao-bo', name: 'Mì xào bò', kcal: 650, unit: '1 dĩa', cat: 'bun-pho' },
    { id: 'mi-goi', name: 'Mì gói (1 gói + trứng)', kcal: 450, unit: '1 tô', cat: 'bun-pho' },
    { id: 'mien-ga', name: 'Miến gà', kcal: 350, unit: '1 tô', cat: 'bun-pho' },
    { id: 'banh-canh-cua', name: 'Bánh canh cua', kcal: 500, unit: '1 tô', cat: 'bun-pho' },
    { id: 'lau-1-nguoi', name: 'Lẩu (phần 1 người, có bún)', kcal: 700, unit: '1 phần', cat: 'bun-pho' },

    // ── Bánh / Xôi ───────────────────────────────────
    { id: 'banh-mi-thit', name: 'Bánh mì thịt', kcal: 450, unit: '1 ổ', cat: 'banh-xoi' },
    { id: 'banh-mi-trung', name: 'Bánh mì ốp la', kcal: 400, unit: '1 ổ', cat: 'banh-xoi' },
    { id: 'banh-mi-cha-ca', name: 'Bánh mì chả cá', kcal: 420, unit: '1 ổ', cat: 'banh-xoi' },
    { id: 'banh-mi-khong', name: 'Bánh mì không', kcal: 230, unit: '1 ổ', cat: 'banh-xoi' },
    { id: 'xoi-man', name: 'Xôi mặn (chà bông, lạp xưởng)', kcal: 550, unit: '1 hộp', cat: 'banh-xoi' },
    { id: 'xoi-xeo', name: 'Xôi xéo', kcal: 500, unit: '1 gói', cat: 'banh-xoi' },
    { id: 'xoi-ga', name: 'Xôi gà', kcal: 550, unit: '1 hộp', cat: 'banh-xoi' },
    { id: 'banh-cuon', name: 'Bánh cuốn', kcal: 400, unit: '1 dĩa', cat: 'banh-xoi' },
    { id: 'banh-uot', name: 'Bánh ướt', kcal: 380, unit: '1 dĩa', cat: 'banh-xoi' },
    { id: 'banh-bao', name: 'Bánh bao nhân thịt', kcal: 330, unit: '1 cái', cat: 'banh-xoi' },
    { id: 'banh-xeo', name: 'Bánh xèo', kcal: 400, unit: '1 cái', cat: 'banh-xoi' },
    { id: 'banh-khot', name: 'Bánh khọt', kcal: 450, unit: '1 dĩa 10 cái', cat: 'banh-xoi' },
    { id: 'banh-beo', name: 'Bánh bèo', kcal: 350, unit: '1 khay', cat: 'banh-xoi' },
    { id: 'banh-gio', name: 'Bánh giò', kcal: 440, unit: '1 cái', cat: 'banh-xoi' },
    { id: 'banh-chung-mieng', name: 'Bánh chưng', kcal: 250, unit: '1 miếng 1/8', cat: 'banh-xoi' },
    { id: 'chao-long', name: 'Cháo lòng', kcal: 400, unit: '1 tô', cat: 'banh-xoi' },
    { id: 'chao-ga', name: 'Cháo gà', kcal: 350, unit: '1 tô', cat: 'banh-xoi' },
    { id: 'chao-trang-hot-vit', name: 'Cháo trắng + hột vịt muối', kcal: 300, unit: '1 tô', cat: 'banh-xoi' },

    // ── Đồ uống ──────────────────────────────────────
    { id: 'tra-sua-tran-chau', name: 'Trà sữa trân châu', kcal: 450, unit: 'ly M', cat: 'do-uong' },
    { id: 'tra-sua-khong-tc', name: 'Trà sữa không trân châu', kcal: 300, unit: 'ly M', cat: 'do-uong' },
    { id: 'ca-phe-sua-da', name: 'Cà phê sữa đá', kcal: 150, unit: '1 ly', cat: 'do-uong' },
    { id: 'ca-phe-den', name: 'Cà phê đen (không đường)', kcal: 5, unit: '1 ly', cat: 'do-uong' },
    { id: 'bac-xiu', name: 'Bạc xỉu', kcal: 220, unit: '1 ly', cat: 'do-uong' },
    { id: 'nuoc-mia', name: 'Nước mía', kcal: 180, unit: '1 ly', cat: 'do-uong' },
    { id: 'nuoc-cam', name: 'Nước cam vắt', kcal: 120, unit: '1 ly', cat: 'do-uong' },
    { id: 'sinh-to-bo', name: 'Sinh tố bơ', kcal: 350, unit: '1 ly', cat: 'do-uong' },
    { id: 'sinh-to-xoai', name: 'Sinh tố xoài', kcal: 250, unit: '1 ly', cat: 'do-uong' },
    { id: 'nuoc-dua', name: 'Nước dừa tươi', kcal: 100, unit: '1 trái', cat: 'do-uong' },
    { id: 'tra-dao', name: 'Trà đào cam sả', kcal: 200, unit: 'ly M', cat: 'do-uong' },
    { id: 'tra-tac', name: 'Trà tắc', kcal: 90, unit: '1 ly', cat: 'do-uong' },
    { id: 'sua-tuoi-khong-duong', name: 'Sữa tươi không đường', kcal: 120, unit: 'hộp 180ml', cat: 'do-uong' },
    { id: 'sua-tuoi-co-duong', name: 'Sữa tươi có đường', kcal: 150, unit: 'hộp 180ml', cat: 'do-uong' },
    { id: 'bia', name: 'Bia', kcal: 140, unit: '1 lon 330ml', cat: 'do-uong' },
    { id: 'nuoc-ngot', name: 'Nước ngọt (Coca, Pepsi...)', kcal: 140, unit: '1 lon 330ml', cat: 'do-uong' },
    { id: 'tra-xanh-khong-do', name: 'Trà xanh đóng chai', kcal: 100, unit: '1 chai 455ml', cat: 'do-uong' },

    // ── Ăn vặt / tráng miệng ─────────────────────────
    { id: 'goi-cuon', name: 'Gỏi cuốn', kcal: 90, unit: '1 cuốn', cat: 'an-vat' },
    { id: 'cha-gio', name: 'Chả giò chiên', kcal: 130, unit: '1 cuốn', cat: 'an-vat' },
    { id: 'banh-trang-tron', name: 'Bánh tráng trộn', kcal: 350, unit: '1 bịch', cat: 'an-vat' },
    { id: 'banh-trang-nuong', name: 'Bánh tráng nướng', kcal: 300, unit: '1 cái', cat: 'an-vat' },
    { id: 'ca-vien-chien', name: 'Cá viên chiên', kcal: 300, unit: '1 xiên 5 viên', cat: 'an-vat' },
    { id: 'khoai-tay-chien', name: 'Khoai tây chiên', kcal: 350, unit: '1 phần vừa', cat: 'an-vat' },
    { id: 'ga-ran-1-mieng', name: 'Gà rán', kcal: 300, unit: '1 miếng', cat: 'an-vat' },
    { id: 'hamburger', name: 'Hamburger bò', kcal: 500, unit: '1 cái', cat: 'an-vat' },
    { id: 'pizza-mieng', name: 'Pizza', kcal: 280, unit: '1 miếng 1/8', cat: 'an-vat' },
    { id: 'che-dau', name: 'Chè đậu (đậu xanh/đỏ)', kcal: 250, unit: '1 chén', cat: 'an-vat' },
    { id: 'che-thai', name: 'Chè Thái sầu riêng', kcal: 400, unit: '1 ly', cat: 'an-vat' },
    { id: 'kem-oc-que', name: 'Kem ốc quế', kcal: 200, unit: '1 cây', cat: 'an-vat' },
    { id: 'sua-chua', name: 'Sữa chua', kcal: 100, unit: '1 hũ', cat: 'an-vat' },
    { id: 'sua-chua-khong-duong', name: 'Sữa chua không đường', kcal: 70, unit: '1 hũ', cat: 'an-vat' },
    { id: 'banh-flan', name: 'Bánh flan', kcal: 150, unit: '1 cái', cat: 'an-vat' },
    { id: 'banh-bong-lan', name: 'Bánh bông lan', kcal: 220, unit: '1 miếng', cat: 'an-vat' },
    { id: 'banh-quy', name: 'Bánh quy', kcal: 140, unit: '3 cái', cat: 'an-vat' },
    { id: 'snack-bim-bim', name: 'Snack bim bim', kcal: 160, unit: '1 gói nhỏ', cat: 'an-vat' },
    { id: 'socola', name: 'Sô cô la', kcal: 150, unit: '5 ô vuông', cat: 'an-vat' },
    { id: 'hat-dieu', name: 'Hạt điều rang', kcal: 170, unit: '1 nắm 30g', cat: 'an-vat' },

    // ── Khác (nguyên liệu — để tự ghép bữa cơm nhà) ──
    { id: 'trung-ga-luoc', name: 'Trứng gà luộc', kcal: 70, unit: '1 quả', cat: 'khac' },
    { id: 'trung-chien', name: 'Trứng chiên', kcal: 110, unit: '1 quả', cat: 'khac' },
    { id: 'uc-ga-luoc', name: 'Ức gà luộc/áp chảo', kcal: 165, unit: '100g', cat: 'khac' },
    { id: 'thit-heo-nac', name: 'Thịt heo nạc luộc', kcal: 200, unit: '100g', cat: 'khac' },
    { id: 'thit-ba-roi', name: 'Thịt ba rọi', kcal: 520, unit: '100g', cat: 'khac' },
    { id: 'thit-bo', name: 'Thịt bò xào', kcal: 250, unit: '100g', cat: 'khac' },
    { id: 'ca-hoi', name: 'Cá hồi áp chảo', kcal: 230, unit: '100g', cat: 'khac' },
    { id: 'ca-bien-kho', name: 'Cá biển kho/chiên', kcal: 200, unit: '100g', cat: 'khac' },
    { id: 'tom-luoc', name: 'Tôm luộc/hấp', kcal: 100, unit: '100g', cat: 'khac' },
    { id: 'dau-hu', name: 'Đậu hũ chiên', kcal: 180, unit: '2 miếng', cat: 'khac' },
    { id: 'rau-luoc', name: 'Rau luộc', kcal: 40, unit: '1 dĩa', cat: 'khac' },
    { id: 'rau-xao', name: 'Rau xào dầu', kcal: 120, unit: '1 dĩa', cat: 'khac' },
    { id: 'canh-rau', name: 'Canh rau', kcal: 60, unit: '1 chén', cat: 'khac' },
    { id: 'canh-chua', name: 'Canh chua cá', kcal: 120, unit: '1 chén', cat: 'khac' },
    { id: 'chuoi', name: 'Chuối', kcal: 100, unit: '1 trái', cat: 'khac' },
    { id: 'tao', name: 'Táo', kcal: 80, unit: '1 trái', cat: 'khac' },
    { id: 'cam', name: 'Cam', kcal: 60, unit: '1 trái', cat: 'khac' },
    { id: 'xoai', name: 'Xoài chín', kcal: 150, unit: '1 trái', cat: 'khac' },
    { id: 'dua-hau', name: 'Dưa hấu', kcal: 90, unit: '2 miếng', cat: 'khac' },
    { id: 'khoai-lang-luoc', name: 'Khoai lang luộc', kcal: 130, unit: '1 củ vừa', cat: 'khac' },
    { id: 'yen-mach', name: 'Yến mạch nấu', kcal: 150, unit: '1 chén (40g khô)', cat: 'khac' },
    { id: 'banh-mi-sandwich', name: 'Sandwich lát', kcal: 80, unit: '1 lát', cat: 'khac' },
    { id: 'whey-protein', name: 'Whey protein', kcal: 120, unit: '1 muỗng', cat: 'khac' },
  ];

  if (typeof module !== 'undefined' && module.exports) module.exports = FOODS_DB;
  else root.FOODS_DB = FOODS_DB;
})(typeof window !== 'undefined' ? window : globalThis);
